package(default_visibility = ["//visibility:public"])

exports_files(
    glob(
        [
            "*lexicon.h",
            "*lexicon.cc",
            "*test.cc",
            "_fp*.h",
            "encoded*.h",
            "encoded*.cc",
            "internal/*.h",
            "internal/*.cc",
            "mutable*.h",
            "mutable*.cc",
            "r1*.h",
            "r1*.cc",
            "r2*.h",
            "r2*.cc",
            "s1*.h",
            "s1*.cc",
            "s2*.h",
            "s2*.cc",
        ],
    ) + [
        "thread_testing.h",
        "thread_testing.cc",
    ],
)
