package(default_visibility = ["//visibility:public"])
exports_files(glob(
  include = [
    "internal/*.h", "internal/*.cc",
    "r1*.h","r1*.cc",
    "r2*.h","r2*.cc",
    "s1*.h","s1*.cc",
    "s2*.h","s2*.cc",
    "encoded*.h","encoded*.cc",
    "*lexicon.h","*lexicon.cc",
    "_fp*.h","_fp*.cc",
    "mutable*.h","mutable*.cc",
    "thread_testing.h","thread_testing.cc",
    "*test.h","*test.cc",
  ], 
  exclude=[], 
  exclude_directories=0, 
  allow_empty=True)
)
