[project]
name = "s2geometry"
description = "Computational geometry and spatial indexing on the sphere"
authors = [
    { name = "Brian Miles", email = "selimnairb@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX",
    "License :: OSI Approved :: Apache Software License",
]
dynamic = [
    "version",
]

[project.license]
file = "LICENSE"
content-type = "text/plain"

[project.urls]
Source = "https://github.com/google/s2geometry"

[build-system]
requires = [
    "wheel",
    "setuptools",
    "setuptools_scm[toml]",
    "cmake_build_extension",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false
include-package-data = false
python-requres = ">=3.7"

[tool.setuptools.packages.find]
where = [
    "src",
]
namespaces = false

[tool.setuptools.package-dir]
"" = "src"
