package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bits",
    srcs = ["bit-interleave.cc"],
    hdrs = [
        "bit-interleave.h",
        "bits.h",
    ],
    deps = [
        "//s2/base:types",
    ],
)
